name: Run Crypto Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Har 10 minute mein chalega
  workflow_dispatch:       # Manual Run button ke liye

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Memory file save karne ki permission

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Yahan humne 'google-generativeai' hata kar 'groq' daal diya hai
      - name: Install dependencies
        run: pip install requests groq edge-tts

      - name: Run Script
        env:
          # Tijori se chaabiyan nikalna
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }} # <--- Ye Naya Hai
        run: python bot.py

      - name: Update Memory (last_id.txt)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_id.txt || echo "No new news to save"
          git commit -m "Update Database" || echo "No changes"
          git push || echo "No changes to push"
